# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(906, 715)
        self.Welcom = QtWidgets.QLabel(Form)
        self.Welcom.setGeometry(QtCore.QRect(60, 90, 431, 31))
        self.Welcom.setObjectName("Welcom")
        self.TestMethodLib = QtWidgets.QListView(Form)
        self.TestMethodLib.setGeometry(QtCore.QRect(60, 150, 256, 192))
        self.TestMethodLib.setObjectName("TestMethodLib")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(620, 170, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(120, 520, 531, 101))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Generate = QtWidgets.QPushButton(self.widget)
        self.Generate.setObjectName("Generate")
        self.horizontalLayout.addWidget(self.Generate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Cancel = QtWidgets.QPushButton(self.widget)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout.addWidget(self.Cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Back = QtWidgets.QPushButton(self.widget)
        self.Back.setObjectName("Back")
        self.horizontalLayout.addWidget(self.Back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LIGO Prog Development"))
        self.Welcom.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#55ff00;\">Ligo Filter PGM Platform</span></p></body></html>"))
        self.Generate.setText(_translate("Form", "生成"))
        self.Cancel.setText(_translate("Form", "取消"))
        self.Back.setText(_translate("Form", "撤回"))
